export const T11_SNAPSHOT_ALGORITHM_VERSION = "t11_theme_snapshot_v1";
export const T11_SNAPSHOT_THRESHOLD_VERSION = "v3_mvp_2026_05_10";
export const T11_SNAPSHOT_VERSION = `${T11_SNAPSHOT_ALGORITHM_VERSION}:${T11_SNAPSHOT_THRESHOLD_VERSION}`;

export const T11_SNAPSHOT_DETAIL_METRIC = "t11.theme_snapshot_detail";
export const T8_EXPRESSION_DETAIL_METRIC = "t8.expression_decision_detail";

export const ACTIVE_THEME_STATUSES = [
  "ACTIVE_UNSCANNED",
  "ACTIVE_SCANNED",
  "ACTIVE",
] as const;

export const SNAPSHOT_LOCK_TTL_MS = 30 * 60 * 1_000;

export const SNAPSHOT_REASON_CODES = {
  DEMAND_CONTRADICTED: "DEMAND_CONTRADICTED",
  DEMAND_EVIDENCE_STALE: "DEMAND_EVIDENCE_STALE",
  DEMAND_MECHANISM_SPECIFIC: "DEMAND_MECHANISM_SPECIFIC",
  DEMAND_MULTIPLE_BENEFICIARIES_VALIDATE:
    "DEMAND_MULTIPLE_BENEFICIARIES_VALIDATE",
  DEMAND_ONLY_C_GRADE_EVIDENCE: "DEMAND_ONLY_C_GRADE_EVIDENCE",
  DEMAND_ONLY_D_GRADE_EVIDENCE: "DEMAND_ONLY_D_GRADE_EVIDENCE",
  DEMAND_PROOF_MISSING: "DEMAND_PROOF_MISSING",
  DEMAND_PROVIDER_DATA_GAP: "DEMAND_PROVIDER_DATA_GAP",
  DEMAND_REQUIRED_PROOF_PRESENT: "DEMAND_REQUIRED_PROOF_PRESENT",
  DECISION_BASKET_PREFERRED: "DECISION_BASKET_PREFERRED",
  DECISION_DELAYED_CATCHUP_CANDIDATE: "DECISION_DELAYED_CATCHUP_CANDIDATE",
  DECISION_ETF_PREFERRED: "DECISION_ETF_PREFERRED",
  DECISION_INSUFFICIENT_DATA: "DECISION_INSUFFICIENT_DATA",
  DECISION_LEADER_BUT_EXTENDED: "DECISION_LEADER_BUT_EXTENDED",
  DECISION_NO_TRADE: "DECISION_NO_TRADE",
  DECISION_SINGLE_STOCK_RESEARCH_JUSTIFIED:
    "DECISION_SINGLE_STOCK_RESEARCH_JUSTIFIED",
  DECISION_WATCHLIST_ONLY: "DECISION_WATCHLIST_ONLY",
  DECISION_WRONG_TICKER: "DECISION_WRONG_TICKER",
  DISPERSION_LEADERS_EXTENDED: "DISPERSION_LEADERS_EXTENDED",
  DISPERSION_MULTIPLE_QUALITY_CANDIDATES:
    "DISPERSION_MULTIPLE_QUALITY_CANDIDATES",
  DISPERSION_NO_CLEAR_SINGLE_LEADER: "DISPERSION_NO_CLEAR_SINGLE_LEADER",
  FUNDAMENTAL_REVENUE_GROWING: "FUNDAMENTAL_REVENUE_GROWING",
  LIQUIDITY_ILLIQUID: "LIQUIDITY_ILLIQUID",
  PRICE_LEADER: "PRICE_LEADER",
  PRICE_LEADER_EXTENDED: "PRICE_LEADER_EXTENDED",
  PRICE_RS_VS_THEME_POSITIVE: "PRICE_RS_VS_THEME_POSITIVE",
  PRICE_STALE_DATA: "PRICE_STALE_DATA",
  PRICE_THEME_BASKET_PROXY_USED: "PRICE_THEME_BASKET_PROXY_USED",
  THEME_MECHANISM_SPECIFIC: "THEME_MECHANISM_SPECIFIC",
  THEME_REQUIRED_PROOF_PRESENT: "THEME_REQUIRED_PROOF_PRESENT",
} as const;
