export const T5_OWNERSHIP_FLOW_ALGORITHM_VERSION = "t5_ownership_flow_v1";
export const T7_BASE_RATE_ALGORITHM_VERSION = "t7_base_rate_v1";
export const ADVANCED_THRESHOLD_VERSION = "v3_mvp_2026_05_10";

export const T5_OWNERSHIP_FLOW_SCORE_VERSION = `${T5_OWNERSHIP_FLOW_ALGORITHM_VERSION}:${ADVANCED_THRESHOLD_VERSION}`;
export const T7_BASE_RATE_SCORE_VERSION = `${T7_BASE_RATE_ALGORITHM_VERSION}:${ADVANCED_THRESHOLD_VERSION}`;

export const T5_SIGNAL_LAYER = "T5_OWNERSHIP_FLOW" as const;
export const T7_SIGNAL_LAYER = "T7_BASE_RATE" as const;

export const T5_REASON_CODES = {
  DATA_MISSING: "DATA_MISSING",
  FLOW_13F_DELAYED_DATA: "FLOW_13F_DELAYED_DATA",
  FLOW_CROWDED: "FLOW_CROWDED",
  FLOW_DISTRIBUTION_WARNING: "FLOW_DISTRIBUTION_WARNING",
  FLOW_ETF_ELIGIBLE: "FLOW_ETF_ELIGIBLE",
  FLOW_INSTITUTIONAL_ACCUMULATION: "FLOW_INSTITUTIONAL_ACCUMULATION",
  FLOW_LICENSE_REQUIRED: "FLOW_LICENSE_REQUIRED",
  FLOW_NO_MEANINGFUL_ACCESS: "FLOW_NO_MEANINGFUL_ACCESS",
  FLOW_OWNERSHIP_BROADENING: "FLOW_OWNERSHIP_BROADENING",
} as const;

export const T7_REASON_CODES = {
  BASE_RATE_LOW_SAMPLE_WARNING: "BASE_RATE_LOW_SAMPLE_WARNING",
  BASE_RATE_MIXED: "BASE_RATE_MIXED",
  BASE_RATE_SUPPORTIVE: "BASE_RATE_SUPPORTIVE",
  BASE_RATE_SURVIVORSHIP_WARNING: "BASE_RATE_SURVIVORSHIP_WARNING",
  BASE_RATE_UNFAVORABLE: "BASE_RATE_UNFAVORABLE",
  DATA_MISSING: "DATA_MISSING",
} as const;

export const BASE_RATE_THRESHOLDS = {
  lowSampleMinimum: 30,
  minimumBarsForContext: 1260,
  supportiveMedianReturn3m: 0.08,
  supportiveWinRate3m: 0.6,
  unfavorableMedianReturn3m: 0,
  unfavorableWinRate3m: 0.45,
  unfavorableWorstDecileDrawdown: -0.25,
} as const;
