export const T13_ALERT_ALGORITHM_VERSION = "t13_state_alerts_v1";
export const T13_ALERT_THRESHOLD_VERSION = "v3_mvp_2026_05_10";
export const T13_ALERT_VERSION = `${T13_ALERT_ALGORITHM_VERSION}:${T13_ALERT_THRESHOLD_VERSION}`;

export const ALERT_LOCK_TTL_MS = 15 * 60 * 1_000;
export const ALERT_COOLDOWN_BUSINESS_DAYS = 10;

export const ALERT_STATE_TYPES = {
  CANDIDATE_EXPOSURE_STATE: "candidate_exposure_state",
  CANDIDATE_FINAL_STATE: "candidate_final_state",
  CANDIDATE_FUNDAMENTAL_STATE: "candidate_fundamental_state",
  CANDIDATE_LIQUIDITY_STATE: "candidate_liquidity_state",
  CANDIDATE_PRICE_STATE: "candidate_price_state",
  THEME_DASHBOARD_STATE: "theme_dashboard_state",
} as const;

export const ALERT_TYPES = {
  DELAYED_CATCHUP: "DELAYED_CATCHUP_CANDIDATE",
  DILUTION_WARNING: "DILUTION_RISK_WARNING",
  EXPOSURE_CONFIRMED: "EXPOSURE_CONFIRMED",
  EXPOSURE_REJECTED: "EXPOSURE_REJECTED",
  FINAL_STATE_CHANGED: "FINAL_STATE_CHANGED",
  FUNDAMENTALS_DETERIORATED: "FUNDAMENTALS_DETERIORATED",
  FUNDAMENTALS_VALIDATED: "FUNDAMENTALS_VALIDATED",
  INVALIDATION_TRIGGERED: "INVALIDATION_TRIGGERED",
  LEADER_BUT_EXTENDED: "LEADER_BUT_EXTENDED",
  LIQUIDITY_WARNING: "LIQUIDITY_RISK_WARNING",
  NO_TRADE_TRIGGERED: "NO_TRADE_TRIGGERED",
  PRICE_STATE_CHANGED: "PRICE_STATE_CHANGED",
  THEME_STATE_CHANGED: "THEME_STATE_CHANGED",
} as const;

export const ALERT_REASON_CODES = {
  DELAYED_CATCHUP: "ALERT_DELAYED_CATCHUP",
  DILUTION_WARNING: "ALERT_DILUTION_WARNING",
  EXPOSURE_CONFIRMED: "ALERT_EXPOSURE_CONFIRMED",
  EXPOSURE_REJECTED: "ALERT_EXPOSURE_REJECTED",
  FINAL_STATE_CHANGED: "ALERT_FINAL_STATE_CHANGED",
  FUNDAMENTALS_DETERIORATED: "ALERT_FUNDAMENTALS_DETERIORATED",
  FUNDAMENTALS_VALIDATED: "ALERT_FUNDAMENTALS_VALIDATED",
  INVALIDATION_TRIGGERED: "ALERT_INVALIDATION_TRIGGERED",
  LEADER_BUT_EXTENDED: "ALERT_LEADER_BUT_EXTENDED",
  LIQUIDITY_WARNING: "ALERT_LIQUIDITY_WARNING",
  NO_TRADE_TRIGGERED: "ALERT_NO_TRADE_TRIGGERED",
  PRICE_STATE_CHANGED: "ALERT_PRICE_STATE_CHANGED",
  SUPPRESSED_COOLDOWN: "ALERT_SUPPRESSED_COOLDOWN",
  THEME_STATE_CHANGED: "ALERT_THEME_STATE_CHANGED",
} as const;
