export const T1_EXPOSURE_ALGORITHM_VERSION = "t1_exposure_v1";
export const T1_EXPOSURE_THRESHOLD_VERSION = "v3_mvp_2026_05_10";
export const T1_EXPOSURE_SCORE_VERSION = `${T1_EXPOSURE_ALGORITHM_VERSION}:${T1_EXPOSURE_THRESHOLD_VERSION}`;

export const T1_COMPONENT_MAX = {
  customerEndMarketFit: 10,
  etfThemeBasketMembership: 10,
  excludedCategoryPenalty: 25,
  managementFilingLanguageSupport: 5,
  productBusinessLineMatch: 20,
  revenueExposureToTheme: 35,
  segmentDisclosureSupport: 15,
} as const;

export const T1_CAPS = {
  excludedCategoryDominates: 29,
  keywordOnly: 29,
  manualOnlyMapping: 49,
  noDirectOrIndirectCategory: 29,
  noRevenueOrBusinessLineEvidence: 49,
  sameSectorOnly: 39,
  seedEtfOnly: 29,
} as const;

export const T1_DISPLAY_GROUPS = {
  DIRECT_BENEFICIARY: "Direct beneficiaries",
  INDIRECT_BENEFICIARY: "Watchlist only",
  MAJOR_BENEFICIARY: "Major beneficiaries",
  NARRATIVE_ADJACENT: "Wrong ticker / rejected",
  PARTIAL_BENEFICIARY: "Indirect or partial beneficiaries",
  SAME_SECTOR_ONLY: "Wrong ticker / rejected",
  UNKNOWN: "Review required",
  UNRELATED: "Wrong ticker / rejected",
} as const;

export const T1_REASON_CODES = {
  BUSINESS_LINE_MATCH: "EXPOSURE_BUSINESS_LINE_MATCH",
  CUSTOMER_END_MARKET_FIT: "EXPOSURE_CUSTOMER_END_MARKET_FIT",
  DIRECT_CATEGORY_MATCH: "EXPOSURE_DIRECT_CATEGORY_MATCH",
  EXCLUDED_CATEGORY_MATCH: "EXPOSURE_EXCLUDED_CATEGORY_MATCH",
  FILING_LANGUAGE_SUPPORT: "EXPOSURE_FILING_LANGUAGE_SUPPORT",
  INDIRECT_CATEGORY_MATCH: "EXPOSURE_INDIRECT_CATEGORY_MATCH",
  KEYWORD_ONLY: "EXPOSURE_KEYWORD_ONLY",
  MANUAL_SEED_ONLY: "EXPOSURE_MANUAL_SEED_ONLY",
  MAPPING_REVIEW_REQUIRED: "EXPOSURE_MAPPING_REVIEW_REQUIRED",
  MULTI_ETF_INCLUDED: "EXPOSURE_MULTI_ETF_INCLUDED",
  NARRATIVE_ADJACENT: "EXPOSURE_NARRATIVE_ADJACENT",
  NO_DIRECT_OR_INDIRECT_MATCH: "EXPOSURE_NO_DIRECT_OR_INDIRECT_MATCH",
  NO_REVENUE_LINK: "EXPOSURE_NO_REVENUE_LINK",
  PROVIDER_CALL_FAILED: "EXPOSURE_PROVIDER_CALL_FAILED",
  PROVIDER_UNCONFIGURED: "EXPOSURE_PROVIDER_UNCONFIGURED",
  REVENUE_MATERIALITY_SUPPORT: "EXPOSURE_REVENUE_MATERIALITY_SUPPORT",
  SAME_SECTOR_ONLY: "EXPOSURE_SAME_SECTOR_ONLY",
  SEC_CIK_MISSING: "EXPOSURE_SEC_CIK_MISSING",
  SEED_ETF_INCLUDED: "EXPOSURE_SEED_ETF_INCLUDED",
  SEGMENT_DATA_MISSING: "EXPOSURE_SEGMENT_DATA_MISSING",
  SEGMENT_SUPPORT: "EXPOSURE_SEGMENT_SUPPORT",
  VENDOR_ONLY_WEAK: "EXPOSURE_VENDOR_ONLY_WEAK",
} as const;

export const T1_SIGNAL_LAYER = "T1_EXPOSURE_PURITY" as const;
