export const SECURITY_MASTER_REASON_CODES = {
  ADR_LABELED: "SECURITY_MASTER_ADR_LABELED",
  ADR_TOKEN_MATCH: "SECURITY_MASTER_ADR_TOKEN_MATCH",
  ADR_TOKEN_REJECTED: "SECURITY_MASTER_ADR_TOKEN_REJECTED",
  BLANK_NAME: "SECURITY_MASTER_BLANK_NAME",
  CIK_CONFLICT: "SECURITY_MASTER_CIK_CONFLICT",
  COMMON_STOCK_BLOCKED_BY_FOREIGN_SIGNAL:
    "SECURITY_MASTER_COMMON_STOCK_BLOCKED_BY_FOREIGN_SIGNAL",
  DUPLICATE_PROVIDER_SYMBOL: "SECURITY_MASTER_DUPLICATE_PROVIDER_SYMBOL",
  ETF_FLAG_CONFLICT: "SECURITY_MASTER_ETF_FLAG_CONFLICT",
  EXCLUDED_TEST_ISSUE: "SECURITY_MASTER_EXCLUDED_TEST_ISSUE",
  FIGI_CONFLICT: "SECURITY_MASTER_FIGI_CONFLICT",
  FOREIGN_LISTING_REVIEW_REQUIRED:
    "SECURITY_MASTER_FOREIGN_LISTING_REVIEW_REQUIRED",
  IDENTIFIER_CONFLICT: "SECURITY_MASTER_IDENTIFIER_CONFLICT",
  MISSING_CIK: "SECURITY_MASTER_MISSING_CIK",
  MISSING_FIGI: "SECURITY_MASTER_MISSING_FIGI",
  NON_US_LOCALE: "SECURITY_MASTER_NON_US_LOCALE",
  STATUS_CONFLICT: "SECURITY_MASTER_STATUS_CONFLICT",
  UNEXPECTED_ASSET_TYPE: "SECURITY_MASTER_UNEXPECTED_ASSET_TYPE",
} as const;

export type SecurityMasterReasonCode =
  (typeof SECURITY_MASTER_REASON_CODES)[keyof typeof SECURITY_MASTER_REASON_CODES];
