export const T2_DEMAND_ALGORITHM_VERSION = "t2_economic_demand_v1";
export const T2_DEMAND_THRESHOLD_VERSION = "v3_mvp_2026_05_10";
export const T2_DEMAND_SCORE_VERSION = `${T2_DEMAND_ALGORITHM_VERSION}:${T2_DEMAND_THRESHOLD_VERSION}`;
export const T2_DEMAND_DETAIL_METRIC = "t2.economic_demand_score";
export const T2_PROVIDER_FEED_METRIC = "t2.provider_demand_feed";
export const T2_SIGNAL_LAYER = "T2_ECONOMIC_DEMAND";

export const T2_DEMAND_LOCK_TTL_MS = 30 * 60 * 1_000;

export const DEMAND_STATES = {
  DEMAND_CONFIRMED: "DEMAND_CONFIRMED",
  DEMAND_CONTRADICTED: "DEMAND_CONTRADICTED",
  DEMAND_IMPROVING: "DEMAND_IMPROVING",
  DEMAND_PLAUSIBLE_BUT_UNPROVEN: "DEMAND_PLAUSIBLE_BUT_UNPROVEN",
  DEMAND_WEAK: "DEMAND_WEAK",
  INSUFFICIENT_DATA: "INSUFFICIENT_DATA",
} as const;

export const DEMAND_REASON_CODES = {
  DEMAND_CAPACITY_TIGHTNESS_EVIDENCE: "DEMAND_CAPACITY_TIGHTNESS_EVIDENCE",
  DEMAND_CONTRADICTED: "DEMAND_CONTRADICTED",
  DEMAND_EVIDENCE_STALE: "DEMAND_EVIDENCE_STALE",
  DEMAND_GOVERNMENT_AWARD_SUPPORT: "DEMAND_GOVERNMENT_AWARD_SUPPORT",
  DEMAND_MACRO_CONTEXT_SUPPORT: "DEMAND_MACRO_CONTEXT_SUPPORT",
  DEMAND_MEASURABLE_BACKLOG: "DEMAND_MEASURABLE_BACKLOG",
  DEMAND_MEASURABLE_ORDER_GROWTH: "DEMAND_MEASURABLE_ORDER_GROWTH",
  DEMAND_MECHANISM_SPECIFIC: "DEMAND_MECHANISM_SPECIFIC",
  DEMAND_ONLY_BUZZWORDS: "DEMAND_ONLY_BUZZWORDS",
  DEMAND_ONLY_C_GRADE_EVIDENCE: "DEMAND_ONLY_C_GRADE_EVIDENCE",
  DEMAND_ONLY_D_GRADE_EVIDENCE: "DEMAND_ONLY_D_GRADE_EVIDENCE",
  DEMAND_PRICING_POWER_EVIDENCE: "DEMAND_PRICING_POWER_EVIDENCE",
  DEMAND_PROOF_MISSING: "DEMAND_PROOF_MISSING",
  DEMAND_PROVIDER_DATA_GAP: "DEMAND_PROVIDER_DATA_GAP",
  DEMAND_REQUIRED_PROOF_PRESENT: "DEMAND_REQUIRED_PROOF_PRESENT",
  DEMAND_UNMAPPED_RECIPIENT: "DEMAND_UNMAPPED_RECIPIENT",
} as const;
