export const T8_EXPRESSION_ALGORITHM_VERSION = "t8_expression_decision_v1";
export const T8_EXPRESSION_THRESHOLD_VERSION = "v3_mvp_2026_05_10";
export const T8_EXPRESSION_SCORE_VERSION = `${T8_EXPRESSION_ALGORITHM_VERSION}:${T8_EXPRESSION_THRESHOLD_VERSION}`;
export const T8_SIGNAL_LAYER = "T8_EXPRESSION_DECISION" as const;

export const T8_REASON_CODES = {
  DATA_MISSING: "DATA_MISSING",
  DECISION_BASKET_PREFERRED: "DECISION_BASKET_PREFERRED",
  DECISION_DELAYED_CATCHUP_CANDIDATE: "DECISION_DELAYED_CATCHUP_CANDIDATE",
  DECISION_ETF_PREFERRED: "DECISION_ETF_PREFERRED",
  DECISION_INSUFFICIENT_DATA: "DECISION_INSUFFICIENT_DATA",
  DECISION_INVALIDATED: "DECISION_INVALIDATED",
  DECISION_LEADER_BUT_EXTENDED: "DECISION_LEADER_BUT_EXTENDED",
  DECISION_NON_PARTICIPANT: "DECISION_NON_PARTICIPANT",
  DECISION_NO_TRADE: "DECISION_NO_TRADE",
  DECISION_REJECTED: "DECISION_REJECTED",
  DECISION_SINGLE_STOCK_RESEARCH_JUSTIFIED:
    "DECISION_SINGLE_STOCK_RESEARCH_JUSTIFIED",
  DECISION_WATCHLIST_ONLY: "DECISION_WATCHLIST_ONLY",
  DECISION_WRONG_TICKER: "DECISION_WRONG_TICKER",
  DISPERSION_ETF_COVERAGE_GOOD: "DISPERSION_ETF_COVERAGE_GOOD",
  DISPERSION_ETF_TOO_BROAD: "DISPERSION_ETF_TOO_BROAD",
  DISPERSION_INSUFFICIENT_CANDIDATES: "DISPERSION_INSUFFICIENT_CANDIDATES",
  DISPERSION_LEADERS_EXTENDED: "DISPERSION_LEADERS_EXTENDED",
  DISPERSION_MULTIPLE_QUALITY_CANDIDATES:
    "DISPERSION_MULTIPLE_QUALITY_CANDIDATES",
  DISPERSION_NO_CLEAR_SINGLE_LEADER: "DISPERSION_NO_CLEAR_SINGLE_LEADER",
  DISPERSION_SINGLE_NAME_RISK: "DISPERSION_SINGLE_NAME_RISK",
} as const;

export const T8_REVIEW_PRIORITY_WEIGHTS = {
  dataQualityFreshness: 0.05,
  exposurePurity: 0.25,
  fundamentalValidation: 0.2,
  liquidityQuality: 0.1,
  ownershipFlowAccess: 0,
  priceParticipation: 0.15,
  valuationRoom: 0.15,
} as const;
