export const T6_LIQUIDITY_ALGORITHM_VERSION = "t6_liquidity_fragility_v1";
export const T6_LIQUIDITY_THRESHOLD_VERSION = "v3_mvp_2026_05_10";
export const T6_LIQUIDITY_SCORE_VERSION = `${T6_LIQUIDITY_ALGORITHM_VERSION}:${T6_LIQUIDITY_THRESHOLD_VERSION}`;
export const T6_SIGNAL_LAYER = "T6_LIQUIDITY_DILUTION_FRAGILITY" as const;

export const T6_THRESHOLDS = {
  cashRunwaySevereMonths: 6,
  cashRunwayWarningMonths: 12,
  coreAverageDollarVolumeMin: 20_000_000,
  coreMarketCapMin: 1_000_000_000,
  expandedAverageDollarVolumeMin: 5_000_000,
  expandedMarketCapMin: 300_000_000,
  illiquidAverageDollarVolumeMax: 1_000_000,
  recentOfferingLookbackDays: 120,
  reverseSplitLookbackYears: 3,
  shareCountGrowthHigh: 0.15,
  shareCountGrowthSevere: 0.25,
  shareCountGrowthWarning: 0.1,
} as const;

export const T6_REASON_CODES = {
  DILUTION_LOW_RISK: "DILUTION_LOW_RISK",
  DILUTION_RECENT_OFFERING: "DILUTION_RECENT_OFFERING",
  DILUTION_SEVERE: "DILUTION_SEVERE",
  DILUTION_SHARE_COUNT_WARNING: "DILUTION_SHARE_COUNT_WARNING",
  FRAGILITY_CASH_RUNWAY_LOW: "FRAGILITY_CASH_RUNWAY_LOW",
  FRAGILITY_CONVERTIBLE_DEBT: "FRAGILITY_CONVERTIBLE_DEBT",
  FRAGILITY_GOING_CONCERN: "FRAGILITY_GOING_CONCERN",
  FRAGILITY_NO_MAJOR_FLAGS: "FRAGILITY_NO_MAJOR_FLAGS",
  FRAGILITY_REVERSE_SPLIT_HISTORY: "FRAGILITY_REVERSE_SPLIT_HISTORY",
  LIQUIDITY_CORE_ELIGIBLE: "LIQUIDITY_CORE_ELIGIBLE",
  LIQUIDITY_DOLLAR_VOLUME_HEALTHY: "LIQUIDITY_DOLLAR_VOLUME_HEALTHY",
  LIQUIDITY_DOLLAR_VOLUME_LOW: "LIQUIDITY_DOLLAR_VOLUME_LOW",
  LIQUIDITY_EXPANDED_ELIGIBLE: "LIQUIDITY_EXPANDED_ELIGIBLE",
  LIQUIDITY_ILLIQUID: "LIQUIDITY_ILLIQUID",
  LIQUIDITY_SPECULATIVE_ONLY: "LIQUIDITY_SPECULATIVE_ONLY",
  PROVIDER_CALL_FAILED: "PROVIDER_ENDPOINT_UNAVAILABLE",
  REQUIRED_DATA_MISSING: "DATA_MISSING",
} as const;
