export const T3_FUNDAMENTAL_ALGORITHM_VERSION = "t3_fundamentals_v1";
export const T3_FUNDAMENTAL_THRESHOLD_VERSION = "v3_mvp_2026_05_10";
export const T3_FUNDAMENTAL_SCORE_VERSION = `${T3_FUNDAMENTAL_ALGORITHM_VERSION}:${T3_FUNDAMENTAL_THRESHOLD_VERSION}`;
export const T3_SIGNAL_LAYER = "T3_FUNDAMENTALS" as const;

export const T3_COMPONENT_MAX = {
  accountingDataQuality: 5,
  balanceSheetQuality: 10,
  cashFlowQuality: 15,
  guidanceBacklogSupport: 15,
  marginExpansion: 15,
  revenueAcceleration: 20,
  segmentValidation: 20,
} as const;

export const T3_CAPS = {
  criticalDataMissing: 39,
  marginAndFcfDeteriorating: 49,
  noPartialSegmentSupport: 59,
  severeDilution: 49,
  vendorSecDisagreement: 59,
} as const;

export const T3_REASON_CODES = {
  BALANCE_SHEET_HEALTHY: "FUNDAMENTAL_BALANCE_SHEET_HEALTHY",
  CASH_RUNWAY_LOW: "FUNDAMENTAL_CASH_RUNWAY_LOW",
  CRITICAL_DATA_MISSING: "FUNDAMENTAL_CRITICAL_DATA_MISSING",
  DEBT_RISK: "FUNDAMENTAL_DEBT_RISK",
  FCF_NEGATIVE: "FUNDAMENTAL_FCF_NEGATIVE",
  FCF_POSITIVE: "FUNDAMENTAL_FCF_POSITIVE",
  GROSS_MARGIN_EXPANDING: "FUNDAMENTAL_GROSS_MARGIN_EXPANDING",
  GUIDANCE_SUPPORT: "FUNDAMENTAL_GUIDANCE_SUPPORT",
  INVENTORY_BUILD_WARNING: "FUNDAMENTAL_INVENTORY_BUILD_WARNING",
  MARGIN_COMPRESSING: "FUNDAMENTAL_MARGIN_COMPRESSING",
  OPERATING_MARGIN_EXPANDING: "FUNDAMENTAL_OPERATING_MARGIN_EXPANDING",
  REVENUE_ACCELERATING: "FUNDAMENTAL_REVENUE_ACCELERATING",
  REVENUE_DECLINING: "FUNDAMENTAL_REVENUE_DECLINING",
  REVENUE_GROWING: "FUNDAMENTAL_REVENUE_GROWING",
  SEC_VENDOR_DISAGREEMENT: "FUNDAMENTAL_SEC_VENDOR_DISAGREEMENT",
  SEGMENT_REVENUE_SUPPORT: "FUNDAMENTAL_SEGMENT_REVENUE_SUPPORT",
  SEVERE_DILUTION: "FUNDAMENTAL_SEVERE_DILUTION",
  SHARE_COUNT_RISING: "FUNDAMENTAL_SHARE_COUNT_RISING",
} as const;

export const T3_DATA_REASON_CODES = {
  DATA_MISSING: "DATA_MISSING",
  DATA_VENDOR_DISAGREEMENT: "DATA_VENDOR_DISAGREEMENT",
  PROVIDER_CALL_FAILED: "PROVIDER_ENDPOINT_UNAVAILABLE",
  PROVIDER_UNCONFIGURED: "DATA_MISSING",
} as const;
