export const T4_PRICE_ALGORITHM_VERSION = "t4_price_participation_v1";
export const T4_PRICE_THRESHOLD_VERSION = "v3_mvp_2026_05_10";
export const T4_PRICE_SCORE_VERSION = `${T4_PRICE_ALGORITHM_VERSION}:${T4_PRICE_THRESHOLD_VERSION}`;
export const T4_SIGNAL_LAYER = "T4_PRICE_VALUATION_PARTICIPATION" as const;

export const T4_HISTORY = {
  minimumBarsForState: 220,
  minimumBarsForShortTermMetrics: 70,
  preferredInitialCalendarDays: 365 * 3,
  tradingDays1m: 21,
  tradingDays3m: 63,
  tradingDays6m: 126,
  tradingDays52w: 252,
} as const;

export const T4_THRESHOLDS = {
  distanceFrom20dWarningAtr: 2,
  distanceFrom50dExtendedAtr: 3,
  distanceFrom50dExtremeAtr: 4.5,
  drawdownBrokenFromHigh: -0.25,
  nonParticipantRsVsTheme1mMax: -0.05,
  oneMonthReturnZscoreExtended: 2,
  persistenceDays: 3,
  priceBarsStaleAfterBusinessDays: 2,
  trendBufferAtr: 0.25,
} as const;

export const T4_REASON_CODES = {
  DELAYED_CATCHUP_IMPROVING: "PRICE_DELAYED_CATCHUP_IMPROVING",
  INSUFFICIENT_HISTORY: "PRICE_INSUFFICIENT_HISTORY",
  LEADER: "PRICE_LEADER",
  LEADER_EXTENDED: "PRICE_LEADER_EXTENDED",
  NEEDS_CONSOLIDATION: "PRICE_NEEDS_CONSOLIDATION",
  NON_PARTICIPANT: "PRICE_NON_PARTICIPANT",
  ONE_DAY_SIGNAL_SUPPRESSED: "PRICE_ONE_DAY_SIGNAL_SUPPRESSED",
  OUTRAN_EVIDENCE: "PRICE_OUTRAN_EVIDENCE",
  PARTICIPANT: "PRICE_PARTICIPANT",
  PRICE_BROKEN: "PRICE_BROKEN",
  RS_VS_SECTOR_POSITIVE: "PRICE_RS_VS_SECTOR_POSITIVE",
  RS_VS_THEME_POSITIVE: "PRICE_RS_VS_THEME_POSITIVE",
  STALE_DATA: "PRICE_STALE_DATA",
  THEME_BASKET_PROXY_USED: "PRICE_THEME_BASKET_PROXY_USED",
  TREND_IMPROVING: "PRICE_TREND_IMPROVING",
  VALUATION_EXPENSIVE: "VALUATION_EXPENSIVE",
  VALUATION_EXTREME: "VALUATION_EXTREME",
  VALUATION_INSUFFICIENT_DATA: "VALUATION_INSUFFICIENT_DATA",
  VALUATION_ROOM_AVAILABLE: "VALUATION_ROOM_AVAILABLE",
  VOLUME_CONFIRMATION: "PRICE_VOLUME_CONFIRMATION",
} as const;
