export const THEME_REASON_CODES = {
  DIRECT_CATEGORIES_PRESENT: "THEME_DIRECT_CATEGORIES_PRESENT",
  EXCLUDED_CATEGORIES_PRESENT: "THEME_EXCLUDED_CATEGORIES_PRESENT",
  INVALIDATION_RULES_PRESENT: "THEME_INVALIDATION_RULES_PRESENT",
  MECHANISM_SPECIFIC: "THEME_MECHANISM_SPECIFIC",
  REQUIRED_PROOF_PRESENT: "THEME_REQUIRED_PROOF_PRESENT",
  SEED_SOURCE_PRESENT: "THEME_SEED_SOURCE_PRESENT",
  VALIDATION_FAILED_MISSING_DIRECT_CATEGORIES:
    "THEME_VALIDATION_FAILED_MISSING_DIRECT_CATEGORIES",
  VALIDATION_FAILED_MISSING_EXCLUDED_CATEGORIES:
    "THEME_VALIDATION_FAILED_MISSING_EXCLUDED_CATEGORIES",
  VALIDATION_FAILED_MISSING_INVALIDATION:
    "THEME_VALIDATION_FAILED_MISSING_INVALIDATION",
  VALIDATION_FAILED_MISSING_PROOF: "THEME_VALIDATION_FAILED_MISSING_PROOF",
} as const;
