-- Phase 16 operational job wrappers and backup audit job types.

ALTER TYPE "JobType" ADD VALUE IF NOT EXISTS 'THEME_SCAN_ORCHESTRATION';
ALTER TYPE "JobType" ADD VALUE IF NOT EXISTS 'ECONOMIC_DEMAND_REFRESH';
ALTER TYPE "JobType" ADD VALUE IF NOT EXISTS 'DATABASE_BACKUP';
